### ISSUE TITLE
Automagy has some kind of terrain alteration on generation.

### ISSUE THREAD

**Issue by ryukra** [Tuhljin/Automagy#12]
We are using a combination of biomes o plenty and climate control(a mod which alters the generation to be more like islands and continents) and we are getting really annoying tiny sandislands. We pinpointed your mod as the culprit and I dont know why your mod should do this. Is this some lost code which was there to test some terraingeneration?

**Comment by Tuhljin** [comment]
There is no worldgen in Automagy at this time (unless you count adding to the loot tables), nor has there ever been, in test code or otherwise.

**Comment by ryukra** [comment]
really? it is your mod and its reproduceable.. why could this be? any clue? I'm would be very sad to remove your mod from my modpack now.. T_T 
we tested 4 times with the same seed without and with your mod and it's just your mod.

**Comment by Tuhljin** [comment]
If you're really just disabling Automagy and nothing else in these tests, then it's some sort of weird interaction between mods. Since I don't do any world gen, it's especially weird interaction, perhaps relying on the mod's load order. You should test disabling your world gen mods and leaving Automagy enabled -- you'll see there is no world gen going on from this. You should probably take it up with the mod authors whose mods do world gen.

**Comment by ryukra** [comment]
dude.. thanks for the tip, I put a Z infront of automagy and it was fixed.. sorry for questioning your awesome skills.. XD keep up the good work.. <3

**Comment by KyyLeNB** [comment]
Sorry for commenting on a closed issue, but I have to share my experience with this. My issue was that my freshly generated worlds were overfilled with HUGE (I mean huuuuuuuge) Mushroom Island biomes. After removing Automagy not only did the worlds contain no MI biomes, they looked totally different (spawn, terrain, biome variation). I messed around with same seeds on worlds with/without Automagy. However this weird generation interaction WAS GONE after renaming mod archive, just as ryukra did. It seems this fixed the whole issue. I would never think it could be caused by such thing. Thanks, both of you ;)
