### ISSUE TITLE
Crash with version 0.22.2

### ISSUE THREAD

**Issue by Qohelethh** [Tuhljin/Automagy#19]
I'm getting this crash when I try to look at Automagy research in the Thaumonomicon. https://gist.github.com/Qohelethh/eed0c8f7f33bbc38b7a2

**Comment by Tuhljin** [comment]
Does it crash without Optifine?

**Comment by Qohelethh** [comment]
I'll uninstall it and check. Is it possible this is a Forge crash related
to fluid IDs? I'm using Forge version 1291. Does Automagy require a newer
version?

**Comment by Qohelethh** [comment]
It doesn't seem to crash without Optifine. However, after the upgrade, all my research in the Automagy tab is reset. I can't purchase some of the researches because they say I need paper, despite the fact that I'm playing on easy mode. In addition, when I click on the research icons that say "click to purchase," it always causes my client to disconnect from the server.

**Comment by Tuhljin** [comment]
I haven't reproduced this problem and don't have any other reports like this. This could be the result of a mod conflict. You may need to do some investigation / process of elimination to determine where the issue is coming from.

Oh, and I'm using both Forge 1230 and Forge 1291 for development and testing.

**Comment by Qohelethh** [comment]
I removed and reinstalled all the mods in question, and can no longer reproduce the crash or the odd behavior in the Thaumonomicon. It's very strange, but everything is working great.
