### ISSUE TITLE
Crash with redlogic circuit

### ISSUE THREAD

**Issue by Xavion3** [Tuhljin/Automagy#33]
http://pastebin.com/rJqhpP1Z

I had a circuit set up to be a half adder but upon inputting redstone signal instead of working correctly it powered up redstone through the other input instead of an output, I then powered up the other input after resetting things and now the game crashes with that error when loading the world.

**Comment by Tuhljin** [comment]
I'm not exactly sure how you've got things laid out when this happens. If you're able to reliably recreate this problem in test worlds, could you send a screenshot of the setup where you encounter it (or multiple screenshots if necessary to convey where all the pieces go)? It sounds like it crashes as soon as you place a certain piece down, so instead of placing that last piece, you could put down, say, a torch (non-redstone, of course) in that position and just tell me what it is that goes there.

**Comment by Xavion3** [comment]
I tried but couldn't get it to crash again despite trying what I think is the same steps sorry, I did get some incredibly bizarre behaviour but it's a RedLogic bug as far as I can tell as it happens with vanilla redstone as well.

**Comment by Tuhljin** [comment]
Closing this. Feel free to reopen if you find more info and perhaps something should be done on my end.
