### ISSUE TITLE
Thirsty Tank not respecting finite water

### ISSUE THREAD

**Issue by Timeslice42** [Tuhljin/Automagy#41]
In what appears to be an optomization when extracting water the thirsty tank doesn't actually remove the liquid. This isn't a huge issue in our modpack, because by the time you can make a thirsty tank you will also have access to infinite water sources.

This is, however, an issue when one is attemtping to use the thristy tank to empty out a lake. Can we get a config option (default off) to have the tank actually remove water source blocks instead of just pretending?

**Comment by Tuhljin** [comment]
Sorry for not replying sooner. For some reason, I didn't see an indicator that an issue was added.

There is already a config option:

>    # Should thirsty tanks preserve water source blocks next to them
>    B:thirstytank_preserve_water_source=true

Does this not suffice?

**Comment by Timeslice42** [comment]
That's exactly what I wanted, thank you :)

**Comment by Tuhljin** [comment]
Yes, if you set it to false, it will treat water like it does other source blocks. However, it doesn't do anything special to them, either, which means (due to water's "infinite" generation rules) the lake might not be completely cleared due to more water source blocks being created.

If you're playing with other mods that give water special rules to make it a limited resource, you might also be interested in these other config options:

>     # Should thirsty tanks slowly fill with water if exposed to the sky while it is raining
>     B:thirstytank_drink_rain=true

>     # How much water (in mB) a water bottle is considered to contain. 0 (default) means bottles can be filled from and emptied into Automagy tanks without changing the amount in a tank. -1 means empty and water bottles won't interact with Automagy tanks. -2 means bottles should use the fluid amount registered with Forge (normally 1000).
>     I:waterbottle_amount=0

**Comment by Timeslice42** [comment]
Great, thanks!
