### ISSUE TITLE
Nethermind Diagram is Wrong 

### ISSUE THREAD

**Issue by Dream-Master** [Tuhljin/Automagy#55]
Nethermind Diagram is show wrong recipe.

https://github.com/GTNewHorizons/NewHorizons/issues/918

**Comment by Tuhljin** [comment]
It isn't wrong. If built as indicated, it will work. Have you actually tried building it as shown, or are you following the lead of others who have said it needs 2 blocks below for each arm? Perhaps you are confused as to what is shown.

There are two layers in the diagram. I generally don't see much confusion over the layout of the top layer. The bottom layer indicates four pieces go below the top to complete the four "arms" of the structure, and I don't know how I could make that any more clear in the diagram (but perhaps the text could be more clear). I've seen some people interpret it as 3 layers but, if this were so, then there would be 8 blocks below the top part of the structure (2 for each arm), not 4 (1 for each arm).

I will admit that the diagram isn't ideal but the "recipe" is accurate and that is simply how Thaumcraft displays that recipe.

**Comment by Dream-Master** [comment]
I only linke the issue from another player on my server. I will say him to look into it.

**Comment by Kairi-lol** [comment]
When i built it the way i showed it worked

**Comment by Kairi-lol** [comment]
When i built it the way the diagram showed it dident work

**Comment by Kairi-lol** [comment]
It only works the way i built it ive tryed it alot of outher ways

**Comment by Kairi-lol** [comment]
You can set the recipy as a picture btw it dosent have to be the arcane construct page it can be a .png

**Comment by Tuhljin** [comment]
> When i built it the way the diagram showed it dident work

You must be misinterpreting the diagram, then. Build it the way you have in your screenshot except, instead of two blocks below the top layer, only put one block. It should work. That's how I always build it. I've seen others build it that way, in person and in videos. There's even a screenshot of it built that way in the Thaumonomicon under Dimensional Lure.

**Comment by Kairi-lol** [comment]
Maby its a bug clientside?

**Comment by Dream-Master** [comment]
@Mylezz is a visual think you look into 3d try to look 2D then it shows correct. The Obsidiand Blocks on the Fronte are hided i guess.

**Comment by Tuhljin** [comment]
There is nothing hidden in the diagram. All blocks are accounted for. Like I said, the diagram shows two layers. All four of the blocks on the bottom are part of _one_ layer. Compare the top layer to the bottom. The four blocks on the edge of the top are in the same position as the blocks on the bottom layer. They're just one y-level down. Maybe this picture will help illustrate what I'm talking about.
![nethermind-recipe-exp2](https://cloud.githubusercontent.com/assets/7244532/21586742/86f00e6c-d091-11e6-9b89-39be8739fe04.png)

It can be confusing due to the way layers are displayed without any depth, but it's still an accurate representation.

**Comment by Dream-Master** [comment]
ok but if i understand @Mylezz right he needs 2 layers of Obsidian under the Platform.

**Comment by Tuhljin** [comment]
Well, I don't, so I don't see how he could.

**Comment by Kairi-lol** [comment]
That makes more sence that diagram was confusing il test it 
When i get on today

**Comment by Kairi-lol** [comment]
yeas @Tuhljin your correct it only uses the one block down like shown in the book ,_However The Diagram is VERRY confusing._

thanks for making this Amazing mod and quickly responding,
it turned out to be a _Glitched block_ on my setup as so it would not function, and now its working as its shown in the book entry

~Thanks
Mylez_

**Comment by Dream-Master** [comment]
Ok then I close this now. Thanks for help.
